// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ70Y-ND8o4O53gLDbEg_gumVR6k_W6Z4',
    appId: '1:381463249837:web:b59edd58ff6cdadbf55724',
    messagingSenderId: '381463249837',
    projectId: 'notification-ecommerce-app',
    authDomain: 'notification-ecommerce-app.firebaseapp.com',
    storageBucket: 'notification-ecommerce-app.firebasestorage.app',
    measurementId: 'G-1TZZRPZZHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYNha0lBgto0DDBQ4XZvmefa3FvEvHH8',
    appId: '1:381463249837:android:c87d123b3e976515f55724',
    messagingSenderId: '381463249837',
    projectId: 'notification-ecommerce-app',
    storageBucket: 'notification-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAINyqFtxSNM9yvF1opH8Ijf0zoTWKZj_s',
    appId: '1:381463249837:ios:43f49fce6d8b23c5f55724',
    messagingSenderId: '381463249837',
    projectId: 'notification-ecommerce-app',
    storageBucket: 'notification-ecommerce-app.firebasestorage.app',
    iosClientId: '381463249837-qq618l1fop6v9r1jjonusuuu9dvmbiun.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAINyqFtxSNM9yvF1opH8Ijf0zoTWKZj_s',
    appId: '1:381463249837:ios:43f49fce6d8b23c5f55724',
    messagingSenderId: '381463249837',
    projectId: 'notification-ecommerce-app',
    storageBucket: 'notification-ecommerce-app.firebasestorage.app',
    iosClientId: '381463249837-qq618l1fop6v9r1jjonusuuu9dvmbiun.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ70Y-ND8o4O53gLDbEg_gumVR6k_W6Z4',
    appId: '1:381463249837:web:35c9dc27281cb0f1f55724',
    messagingSenderId: '381463249837',
    projectId: 'notification-ecommerce-app',
    authDomain: 'notification-ecommerce-app.firebaseapp.com',
    storageBucket: 'notification-ecommerce-app.firebasestorage.app',
    measurementId: 'G-E9M27MNR3Z',
  );

}